apiVersion: v2
type: application

# Information about clowder.
name: clowder2
icon: https://isda.ncsa.illinois.edu/~kooper/charts/images/clowder.png
home: https://clowderframework.org/
description: >
  Open Source Data Management for Long Tail Data. Clowder is a customizable and
  scalable data management framework to support any data format and multiple
  research domains.

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.9.3

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "2.0.0-beta.3"

# List of people that maintain this helm chart.
maintainers:
  - name: Rob Kooper
    email: kooper@illinois.edu
  - name: Chen Wang
    email: cwang138@illinois.edu

# location of source code
sources:
  - https://github.com/clowder-framework/clowder2

# Dependencies for clowder. Some of the dependencies are only installed if they
# are enabled.
dependencies:
  - name: mongodb
    version: ~12
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/
    condition: mongodb.enabled
  - name: minio
    version: ~12
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/
    condition: minio.enabled
  - name: rabbitmq
    version: ~10
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/
    condition: rabbitmq.enabled
  - name: elasticsearch
    version: ~19
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/
    condition: elasticsearch.enabled
  - name: keycloak
    version: ~13
    repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/
    condition: keycloak.enabled
