site_name: Clowder
repo_url: https://github.com/clowder-framework/clowder2
edit_uri: mkdocs/docs
nav:
  - Home: index.md
  - User Guide:
      - users/index.md
      - Visualizations: users/visualizations.md
  - Developer Guide:
      - Getting started: devs/getstarted.md
      - Architecture: devs/architecture.md
      - Keycloak: devs/keycloak.md
      - Metadata: devs/metadata.md
      - Mongo: devs/mongo-fastapi.md
      - PyCharm: devs/pycharm.md
      - Elasticsearch: devs/elasticsearch.md
      - Listeners: devs/listeners.md
      - VM Setup: devs/vm-setup.md
      - Proposals:
        - Storage: devs/storage.md
  - About: about.md

theme:
  name: material
  site_description: "Clowder v2 Documentation"
  custom_dir: docs/overrides
  features:
    - navigation.tabs
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/favicon.png
  logo: assets/images/cat.png
  palette:
    scheme: clowder

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/clowder-framework
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/orgs/clowder/repositories
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pyclowder
    - icon: fontawesome/brands/slack
      link: https://clowder-software.slack.com
